WEIGHTS:
  NAV: "weights/CUTOUT_WT_True_SD_200_ckpt.99.pvp.pth"
  # GAZE: "weights/gaze_normal_32_seed300_1649708927_ckpt.49.pth"
  # PLACE: "weights/speed_sweep_seed2_speed0.174533_1648669786.ckpt.94.pth"
  # MIXER: "weights/sweep_17_SD_200_1651156250_ckpt.12.pth"
# new
  # NAV: "weights/final_paper/nav_CUTOUT_WT_True_SD_300_ckpt.90.pth"
  GAZE: "weights/final_paper/gaze_normal_32_seed100_1649708902_ckpt.38.pth"
  PLACE: "weights/final_paper/place_10deg_32_seed300_1649709235_ckpt.75.pth"
  MIXER: "weights/final_paper/final_moe_rnn_60_1.0_SD_100_1652120928_ckpt.16_copy.pth"
  # MIXER: "weights/final_gater_rnn_60_1.0_SD_300_1652203350_ckpt_55.pth"
  MRCNN: "weights/ikea_apricot_large_only_model_0002999.pth"
  MRCNN_50: "weights/ikea_apricot_r50_normal_100_output_model_0003599.pth"
  DEBLURGAN: "weights/fpn_inception.h5"

DEVICE: "cpu"
USE_REMOTE_SPOT: False
PARALLEL_INFERENCE_MODE: True

# General env params
CTRL_HZ: 2.0
MAX_EPISODE_STEPS: 500

# Nav env
SUCCESS_DISTANCE: 0.3
SUCCESS_ANGLE_DIST: 5
DISABLE_OBSTACLE_AVOIDANCE: True
USE_OA_FOR_NAV: True
USE_HEAD_CAMERA: True

# Gaze env
CENTER_TOLERANCE: 0.3
OBJECT_LOCK_ON_NEEDED: 3
TARGET_OBJ_NAME: "rubiks_cube"
DONT_PICK_UP: False
ASSERT_CENTERING: True

# Place env
EE_GRIPPER_OFFSET: [0.2, 0.0, 0.05]
SUCC_XY_DIST: 0.1
SUCC_Z_DIST: 0.20

# Base action params
MAX_LIN_DIST: 0.25  # meters
MAX_ANG_DIST: 15.0  # degrees

# Arm action params
MAX_JOINT_MOVEMENT: 0.0872665  # Gaze arm speed (5 deg)
MAX_JOINT_MOVEMENT_2: 0.174533  # Place arm speed (6 deg)
INITIAL_ARM_JOINT_ANGLES: [0, -170, 120, 0, 75, 0]
GAZE_ARM_JOINT_ANGLES: [0, -160, 100, 0, 90, 0]
PLACE_ARM_JOINT_ANGLES: [0, -170, 120, 0, 75, 0]
ARM_LOWER_LIMITS: [-45, -180, 0, 0, -90, 0]
ARM_UPPER_LIMITS: [45, -45, 180, 0, 90, 0]
JOINT_BLACKLIST: [3, 5] # joints we can't control "arm0.el0", "arm0.wr1"
ACTUALLY_MOVE_ARM: True
GRASP_EVERY_STEP: False
TERMINATE_ON_GRASP: False

# Mask RCNN
GRAYSCALE_MASK_RCNN: False
USE_MRCNN: True
USE_FPN_R50: False
USE_DEBLURGAN: False
IMAGE_SCALE: 0.7
# After this many time steps of not seeing the current target object, we become open to looking for new ones
FORGET_TARGET_OBJECT_STEPS: 15

# Docking (currently only used by ASC, Seq Exp and Language env)
RETURN_TO_BASE: True

# For Semantic Map
MAP_SIZE_CM: 1000 # 1000cm = 10 meter
MAP_RESOLUTION: 2 # 1 cell = 2 cm -> 500 cell for the global map
GLOBAL_DOWNSCALING: 2 # 250 cell for the local map
VISION_RANGE: 125 # 125*2 = 250 cm = 2.5m
HFOV: 55
DU_SCALE: 1
CAT_PRED_THRESHOLD: 1.0
EXP_PRED_THRESHOLD: 5.0
MAP_PRED_THRESHOLD: 5.0
NUM_SEM_CATEGORIES: 17
CAMERA_HEIGHT: 0.736317
NUM_PROCESSES: 1
FRONTIER_EXPLORE_RADIUS: 5
VISUALIZE: True
DETECTION_MODEL: "owlvit" # In the current stage, we only clear up the code for owlvit
OBS_DILATION_SELEM_RADIUS: 5
GOAL_DILATION_SELEM_RADIUS: 5
MIN_OBS_DILATION_SELEM_RADIUS: 1
AGENT_CELL_RADIUS: 1
GOAL_TOLERANCE: 0.01
CONTINUOUS_ANGLE_TOLERANCE: 30.0
COLLISION_THRESHOLD: 0.8
TURN_ANGLE: 9.6
MIN_DEPTH: 0.0
MAX_DEPTH: 1.7
ENV_FRAME_WIDTH: 640
ENV_FRAME_HEIGHT: 480
FRAME_WIDTH: 160
FRAME_HEIGHT: 120
PLANNER: "frontier"
EXP_NAME: spot_sem_exp
UPDATE_PERIOD: 0.2
BASE_ANGULAR_VEL: 0.872665
BASE_LIN_VEL: 0.75
DUMP_LOCATION: "./tmp/"
NUM_LOCAL_STEPS: 25
NUM_GLOBAL_STEPS: 20
GOAL_CAT_ID: 0
