repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        exclude: |
            (?x)^(
                mask_rcnn_detectron2/
                | habitat-lab/
                | DeblurGANv2/
            )
            
  - repo: https://github.com/pycqa/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: |
            (?x)^(
                mask_rcnn_detectron2/
                | habitat-lab/
                | DeblurGANv2/
            )

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                mask_rcnn_detectron2/
                | habitat-lab/
                | DeblurGANv2/
            )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive, --no-strict-optional, --ignore-missing-imports]
        exclude: |
            (?x)^(
                mask_rcnn_detectron2/
                | habitat-lab/
                | DeblurGANv2/
            )