version: 2.1

gpu: &gpu
  machine:
    image: ubuntu-2004-cuda-11.4:202110-01
  resource_class: gpu.nvidia.medium
  environment:
    FPS_THRESHOLD: 900

jobs:
  pre-commit:
    working_directory: ~/repo/
    resource_class: small
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Running precommit checks
          command: |
            pip install pre-commit
            pre-commit install-hooks
            pre-commit run --all-files

workflows:
  main:
    jobs:
      - pre-commit
